### ISSUE TITLE
how to run and get_start?

### ISSUE THREAD

**Issue by SeekPoint** [beopst/dcn.tf#4]

**Comment by beopst** [comment]
First, generate cluttered MNIST datasets using [this code](https://github.com/deepmind/mnist-cluttered). As you can see in mnist_input.py, filename should have id_label.png format. Then, revise dataset path in train.py.

**Comment by SeekPoint** [comment]
what's id_label.png come from ?

after I run 'mnist-cluttered' and had the train.py changed its path, it looks like:

index d04e723..4f1a776 100644
--- a/train.py
+++ b/train.py
@@ -37,10 +37,10 @@ def error_rate(predictions, labels):
 def train():
-    trn_data = mnist_input.load_data('data/mnist-cluttered/train')
-    trn_data = mnist_input.load_data('mnist-cluttered/mnist/train.t7')
   n_trn = len(trn_data)
-    val_data = mnist_input.load_data('data/mnist-cluttered/valid', shuffle=False)
-    val_data = mnist_input.load_data('mnist-cluttered/mnist/valid.t7', shuffle=False)
   val_data_x, val_data_y = zip(*val_data)
   n_val = len(val_data)

envy@ub1404:~/os_pri/github/dcn.tf$ 

envy@ub1404:~/os_pri/github/dcn.tf$ tree
.
├── data
│   └── mnist-cluttered
├── mnist-cluttered
│   ├── download_mnist.lua
│   ├── example.lua
│   ├── LICENSE
│   ├── mnist
│   │   ├── t10k-images-idx3-ubyte
│   │   ├── t10k-labels-idx1-ubyte
│   │   ├── test.t7
│   │   ├── train-images-idx3-ubyte
│   │   ├── train-labels-idx1-ubyte
│   │   ├── train.t7
│   │   └── valid.t7
│   ├── mnist_cluttered.lua
│   └── README.md
├── mnist_input.py
├── mnist_input.pyc
├── models
│   ├── dcn.py
│   ├── dcn.pyc
│   ├── **init**.py
│   ├── **init**.pyc
│   ├── only_coarse.py
│   └── only_fine.py
├── README.md
├── slim
│   ├── BUILD
│   ├── **init**.py
│   ├── **init**.pyc
│   ├── losses.py
│   ├── losses.pyc
│   ├── ops.py
│   ├── ops.pyc
│   ├── README.md
│   ├── scopes.py
│   ├── scopes.pyc
│   ├── slim.py
│   ├── slim.pyc
│   ├── variables.py
│   └── variables.pyc
├── train.py

**Comment by beopst** [comment]
This code needs individual images for training.
Please refer to the below lua script to generate dataset as images.
1. create directory to store png files (e.g., ./train, ./val, ./tst)
2. put the below script to mnist-cluttered/.
3. revise datasetPath, the number of examples (e.g., 50,000 for training set) and destination for saving images
4. run the script

Cluttered images will be saved in the destination directory with a format of %d_%d.png. The latter indicates the class labels.

``` lua
require 'image'

local mnist_cluttered = require 'mnist_cluttered'

--!!! revise datasetPath !!!
local dataConfig = {datasetPath='mnist/test.t7', megapatch_w=100, num_dist=8}
local dataInfo = mnist_cluttered.createData(dataConfig)
--local observation, target = unpack(dataInfo.nextExample())
--print("observation size:", table.concat(observation:size():totable(), 'x'))
--print("targets:", target)

count = 0 
class_stat = torch.zeros(10)
--!!! revise here !!!
while count < 10000 do
  local observation, target = unpack(dataInfo.nextExample())
  count = count + 1 
  class_stat = class_stat + target
  print(count)

  local formatted = image.toDisplayTensor({input=observation})
  tmp, class_label = torch.max(target,1)
  dst_file = "%d_%d" % {count,class_label[1]-1}
  --!!! revise here !!!
  image.save("test/%s.png"%dst_file, formatted)
end
print(class_stat)
```

**Comment by SeekPoint** [comment]
after running the script above for train/test/valid respectively and success generates the *.png, I start run:

envy@ub1404:~/os_pri/github/dcn.tf$ python train.py 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 150, in main
    train()
  File "train.py", line 44, in train
    val_data_x, val_data_y = zip(*val_data)
ValueError: need more than 0 values to unpack
envy@ub1404:~/os_pri/github/dcn.tf$ 

my tree is:

envy@ub1404:~/os_pri/github/dcn.tf$ tree
.
├── data
│   └── mnist-cluttered
├── mnist-cluttered
│   ├── download_mnist.lua
│   ├── example.lua
│   ├── LICENSE
│   ├── mnist
│   │   ├── t10k-images-idx3-ubyte
│   │   ├── t10k-labels-idx1-ubyte
│   │   ├── test.t7
│   │   ├── train-images-idx3-ubyte
│   │   ├── train-labels-idx1-ubyte
│   │   ├── train.t7
│   │   └── valid.t7
│   ├── mnist_cluttered.lua
│   ├── README.md
│   ├── start_test.lua
│   ├── start_train.lua
│   ├── start_val.lua
│   ├── test
│   │   ├── 10000_7.png
│   │   ├── 1000_1.png
│   │   ├── 1001_4.png
.............................
└── valid
│       ├── 10000_3.png
│       ├── 1000_9.png
│       ├── 1001_4.png
│       ├── 1002_7.png
.....................................
│   ├── train
│   │   ├── 10000_6.png
│   │   ├── 10001_1.png
│   │   ├── 10002_7.png
│   │   ├── 10003_4.png
├── mnist_input.py
├── mnist_input.pyc
├── models
│   ├── dcn.py
│   ├── dcn.pyc
│   ├── **init**.py
│   ├── **init**.pyc
│   ├── only_coarse.py
│   └── only_fine.py
├── README.md
├── slim
│   ├── BUILD
│   ├── **init**.py
│   ├── **init**.pyc
│   ├── losses.py
│   ├── losses.pyc
│   ├── ops.py
│   ├── ops.pyc
│   ├── README.md
│   ├── scopes.py
│   ├── scopes.pyc
│   ├── slim.py
│   ├── slim.pyc
│   ├── variables.py
│   └── variables.pyc
├── train.py

**Comment by beopst** [comment]
val_data is zip(image,label), i.e. a list of 2-tuple (please see mnist_input.py). I think you should verify the contents in val_data variable.

**Comment by SeekPoint** [comment]
A wrong dir location caused this.
thanks
