### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by SeekPoint** [beopst/dcn.tf#5]
envy@ub1404:~/os_pri/github/dcn.tf$ python train.py 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 150, in main
    train()
  File "train.py", line 44, in train
    val_data_x, val_data_y = zip(*val_data)
ValueError: need more than 0 values to unpack
envy@ub1404:~/os_pri/github/dcn.tf$

**Comment by beopst** [comment]
Please refer to #4 . The generated files should be a format of id_label.png.
